"""remove some fields

Revision ID: b975a12b9a1a
Revises: f9f1a26f8031
Create Date: 2025-11-05 08:41:59.446290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b975a12b9a1a'
down_revision = 'f9f1a26f8031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
